### ISSUE TITLE
Sample code build failed

### ISSUE THREAD

**Issue by zhoushuntong** [intel/SGXDataCenterAttestationPrimitives#109]
SampleCode/QuoteGenerationSample$ sudo make
make target
make[1]: Entering directory '/home/rigsec/sgx-file/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample'
App/App.cpp:50:10: fatal error: sgx_dcap_ql_wrapper.h: No such file or directory
 #include "sgx_dcap_ql_wrapper.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:174: recipe for target 'App/App.o' failed
make[1]: *** [App/App.o] Error 1
make[1]: Leaving directory '/home/rigsec/sgx-file/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample'
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hyjiang** [comment]
You need to install "libsgx-dcap-ql" and "libsgx-dcap-ql-dev" packages before make Samplecode.

**Comment by zhoushuntong** [comment]
> You need to install "libsgx-dcap-ql" and "libsgx-dcap-ql-dev" packages before make Samplecode.

thanks !!!! build ok, but run the app with error like below 

/SampleCode/QuoteGenerationSample$ sudo ./app 
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe019

**Comment by hyjiang** [comment]
Suppose you need to follow PCCS README to setup a PCCS server.

https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs

**Comment by Ruoyu-y** [comment]
> Suppose you need to follow PCCS README to setup a PCCS server.
> 
> https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs

Hi, I'm facing the same problem and i tried to setup the PCCS server according to the README. But i after installing the PCCS server, i could see the PCCS service kept restarting. Any suggestion for that?

**Comment by jsun39** [comment]
I guess that some components are not installed correctly, you could check you pccs's log: logs/pccs_server.log

**Comment by Ruoyu-y** [comment]
> I guess that some components are not installed correctly, you could check you pccs's log: logs/pccs_server.log

Both the pccs-out-0.log and pccs-error-0.log are empty. May i ask what're the dependencies to run sample code, except QuoteGeneration lib, QuoteProvider lib, pccs server? Thanks

**Comment by lingyuj** [comment]
> > I guess that some components are not installed correctly, you could check you pccs's log: logs/pccs_server.log
> 
> Both the pccs-out-0.log and pccs-error-0.log are empty. May i ask what're the dependencies to run sample code, except QuoteGeneration lib, QuoteProvider lib, pccs server? Thanks

Did you setup PCCS by installing the sgx-dcap-pccs package? Then you can check the log file in /opt/intel/sgx-dcap-pccs/logs/

**Comment by Ruoyu-y** [comment]
> > > I guess that some components are not installed correctly, you could check you pccs's log: logs/pccs_server.log
> > 
> > 
> > Both the pccs-out-0.log and pccs-error-0.log are empty. May i ask what're the dependencies to run sample code, except QuoteGeneration lib, QuoteProvider lib, pccs server? Thanks
> 
> Did you setup PCCS by installing the sgx-dcap-pccs package? Then you can check the log file in /opt/intel/sgx-dcap-pccs/logs/

I installed the PCCS thru the manual installation guide in linux. Shall the logs located in ~/.pm2/logs?

**Comment by lingyuj** [comment]
Can you check the logs folder in the source directory?

**Comment by hyjiang** [comment]
> > Can you check the logs folder in the source directory?
> 
> I still cannot find logs inside the folder, however, using 'pm2 logs', i'm able to find sth like this：
> PM2 | 2020-09-11T14:21:50: PM2 log: App name:pccs id:0 disconnected
> PM2 | 2020-09-11T14:21:50: PM2 log: App [pccs:0] exited with code [0] via signal [SIGILL]
> PM2 | 2020-09-11T14:21:50: PM2 log: Script /home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/pccs_server.js had too many unstable restarts (5). Stopped. "errored"
> 
> Any suggestions? Thanks.

If you installed PCCS manually, then pls find the log in folder pccs/logs

**Comment by lingyuj** [comment]
> > Can you check the logs folder in the source directory?
> 
> I still cannot find logs inside the folder, however, using 'pm2 logs', i'm able to find sth like this：
> PM2 | 2020-09-11T14:21:50: PM2 log: App name:pccs id:0 disconnected
> PM2 | 2020-09-11T14:21:50: PM2 log: App [pccs:0] exited with code [0] via signal [SIGILL]
> PM2 | 2020-09-11T14:21:50: PM2 log: Script /home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/pccs_server.js had too many unstable restarts (5). Stopped. "errored"
> 
> Any suggestions? Thanks.

Try this:
go to pccs/config folder, copy production-0.json to default.json
then go to pccs/ foder, run node pccs_server.js

**Comment by Ruoyu-y** [comment]
> > > Can you check the logs folder in the source directory?
> > 
> > 
> > I still cannot find logs inside the folder, however, using 'pm2 logs', i'm able to find sth like this：
> > PM2 | 2020-09-11T14:21:50: PM2 log: App name:pccs id:0 disconnected
> > PM2 | 2020-09-11T14:21:50: PM2 log: App [pccs:0] exited with code [0] via signal [SIGILL]
> > PM2 | 2020-09-11T14:21:50: PM2 log: Script /home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/pccs_server.js had too many unstable restarts (5). Stopped. "errored"
> > Any suggestions? Thanks.
> 
> Try this:
> go to pccs/config folder, copy production-0.json to default.json
> then go to pccs/ foder, run node pccs_server.js

I tried the steps you provided, and here's the result.
ubuntu@ubuntu:~/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs$ node pccs_server.js 


#
# Fatal error in , line 0
# Check failed: result.second.
#
#
#
#FailureMessage Object: 0x7ffe7737cfb0
 1: 0xa6f5f1  [node]
 2: 0x19cb8c4 V8_Fatal(char const*, ...) [node]
 3: 0xe58379 v8::internal::GlobalBackingStoreRegistry::Register(std::shared_ptr<v8::internal::BackingStore>) [node]
 4: 0xba38a8 v8::ArrayBuffer::GetBackingStore() [node]
 5: 0x9c1290 napi_get_typedarray_info [node]
 6: 0x7fe50004d4d0  [/home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 7: 0x7fe50005166f FFI::FFI::InitializeBindings(Napi::Env, Napi::Object) [/home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 8: 0x7fe500052760  [/home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/node_modules/ffi-napi/build/Release/ffi_bindings.node]
 9: 0x7fe50004d5b4 __napi_Init(napi_env__*, napi_value__*) [/home/ubuntu/SGXDataCenterAttestationPrimitives/QuoteGeneration/pccs/node_modules/ffi-napi/build/Release/ffi_bindings.node]
10: 0x9d47b8 napi_module_register_by_symbol(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Context>, napi_value__* (*)(napi_env__*, napi_value__*)) [node]
11: 0x9d8c04  [node]
12: 0x9d7f2b node::binding::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [node]
13: 0xbe254b  [node]
14: 0xbe3af6  [node]
15: 0xbe4176 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [node]
16: 0x13fe0b9  [node]
Illegal instruction (core dumped)

Really don't know what's the problem... Can you help point out the root cause for that?
