### ISSUE TITLE
[Driver] mmput_async can't be used

### ISSUE THREAD

**Issue by jhand2** [intel/SGXDataCenterAttestationPrimitives#127]
For kernels 5.0 to 5.3, the Linux dcap driver uses mmput_async instead of mmput. The issue is that mmput_async is not an exported symbol, a dkms module will fail to build on 5.0 to 5.3 kernels. I don't understand why this condition is there, and think mmput should just be used for all kernels

Code in question in main.c:

```
#if (LINUX_VERSION_CODE < KERNEL_VERSION(5, 0, 0) || LINUX_VERSION_CODE > KERNEL_VERSION(5, 4, 0) )
                mmput(encl_mm->mm);
#else
                mmput_async(encl_mm->mm);
#endif
```

**Comment by haitaohuang** [comment]
hmm, I didn't see issue on 5.3. And just compiled on  5.3.0-62-generic #56~18.04.1-Ubuntu and 5.3.0-1032-azure #33~18.04.1-Ubuntu. 

What are the exact the versions you had failure on?
 
IIRC  the second condition was added because mmput_async was not exported from 5.5, and we had a build error at that time. It probably came back in later versions? And distro/flavor dependent?
 
upstream has been using mmput_async since v21, which is around 5.2 release and for 5.3 RC1

**Comment by jhand2** [comment]
> What are the exact the versions you had failure on?

I don't quite remember, I'll give it another shot again this week and let you know.

> IIRC the second condition was added because mmput_async was not exported from 5.5, and we had a build error at that time. It probably came back in later versions? And distro/flavor dependent?

When I look at the vanilla kernel source, it is not exported. I suppose it could be different on Ubuntu.

> upstream has been using mmput_async since v21, which is around 5.2 release and for 5.3 RC1

Makes sense, upstream isn't a module so it can use unexported functions

**Comment by haitaohuang** [comment]
This issue also settled in https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/135. Though it is still not clear versions of distro kernels exporting mmput_async, the versions we test for Ubuntu and RHEL are all good.

**Comment by jhand2** [comment]
@haitaohuang thanks! Feel free to close this issue when #135 is merged

**Comment by haitaohuang** [comment]
#135 merged and for higher kernel versions, see solution in https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/146
