### ISSUE TITLE
What's the inverse function of `tdx_att_get_quote`?

### ISSUE THREAD

**Issue by 0400H** [intel/SGXDataCenterAttestationPrimitives#317]
Environment：dcap_1.15_reproducible

Get quote from `tdx_report_data_t` : `tdx_att_get_quote`
Get `tdx_report_data_t` from quote : ??

How to achieve it?

**Comment by llly** [comment]
Bytes 568 to 631 of quote. You can calculate it from
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/quote_wrapper/common/inc/sgx_quote_4.h#L143

**Comment by lzha101** [comment]
Looks you just want the report_data_t.  After the above conversion, you need to get the report_data_t field from report_body.
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/quote_wrapper/common/inc/sgx_quote_4.h#L136

BTW,  it is recommended to use the normal release tag instead of the reproducible branch for development.  The reproducible branch is for reproducing the prebuilt binaries.
